# Generated by Django 5.0.1 on 2024-02-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organizer',
            new_name='is_organiser',
        ),
    ]
