# Generated by Django 5.0.1 on 2024-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_cart'),
        ('organisers', '0003_player_alter_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, to='organisers.team'),
        ),
    ]
