# Generated by Django 5.0.1 on 2024-05-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_user_orders_user_orders_success'),
        ('organisers', '0020_match_current_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='organisers.team'),
        ),
    ]
