# Generated by Django 5.0.1 on 2024-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0002_tournament_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='player name')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='organisers.player'),
        ),
    ]
