# Generated by Django 5.0.1 on 2024-03-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0003_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_type', models.CharField(max_length=254, verbose_name='catogory type')),
                ('max_age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='catogories',
            field=models.ManyToManyField(blank=True, related_name='tournament_catagory', to='organisers.catagory'),
        ),
    ]
