# Generated by Django 5.0.1 on 2024-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0004_catagory_tournament_catogories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=254, verbose_name='game type')),
                ('categories', models.ManyToManyField(blank=True, related_name='game_catagory', to='organisers.catagory')),
            ],
        ),
    ]
