# Generated by Django 5.0.1 on 2024-03-28 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0004_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fixtures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='organisers.fixtures'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_category', to='organisers.category'),
        ),
    ]
