# Generated by Django 5.0.1 on 2024-03-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0005_category_fixtures_alter_fixtures_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fixture',
        ),
    ]
