# Generated by Django 5.0.1 on 2024-03-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0005_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
