# Generated by Django 5.0.1 on 2024-03-28 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0006_remove_category_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fixtures',
        ),
        migrations.AddField(
            model_name='category',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_fixture', to='organisers.fixtures'),
        ),
    ]
