# Generated by Django 5.0.1 on 2024-03-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0006_rename_catagory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='catogories',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisers.game'),
        ),
    ]
