# Generated by Django 5.0.1 on 2024-03-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0007_remove_category_fixtures_category_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_category', to='organisers.category'),
        ),
    ]
