# Generated by Django 5.0.1 on 2024-03-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0008_match_match_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='currentMatch',
            field=models.IntegerField(default=0),
        ),
    ]
