# Generated by Django 5.0.1 on 2024-03-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0008_category_price_tournament_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='categories',
            new_name='default_categories',
        ),
    ]
