# Generated by Django 5.0.1 on 2024-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0009_rename_categories_game_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.CharField(blank=True, max_length=254, verbose_name='catogory details'),
        ),
    ]
