# Generated by Django 5.0.1 on 2024-03-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0009_fixtures_currentmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='fixture',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='winners_stages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
