# Generated by Django 5.0.1 on 2024-03-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0011_alter_category_fixture_alter_tournament_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='organisers.team'),
        ),
    ]
