# Generated by Django 5.0.1 on 2024-03-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0012_alter_match_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
