# Generated by Django 5.0.1 on 2024-03-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0013_fixtures_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtures',
            name='currentMatch',
        ),
    ]
