# Generated by Django 5.0.1 on 2024-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0014_remove_fixtures_currentmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='currentBracket',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_bracket', to='organisers.match'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='currentWinners',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_winners', to='organisers.team'),
        ),
    ]
