# Generated by Django 5.0.1 on 2024-04-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0015_alter_fixtures_currentbracket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='currentBracket',
            field=models.ManyToManyField(blank=True, related_name='current_bracket', to='organisers.match'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='currentWinners',
            field=models.ManyToManyField(blank=True, related_name='current_winners', to='organisers.team'),
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('set_no', models.IntegerField(default=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisers.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='sets_scores',
            field=models.ManyToManyField(blank=True, related_name='match_scoreboard', to='organisers.scoreboard'),
        ),
    ]
