# Generated by Django 5.0.1 on 2024-04-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0016_alter_fixtures_currentbracket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='default_categories',
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='court name')),
                ('current_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_match', to='organisers.match')),
                ('tournamet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisers.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_court', to='organisers.court'),
        ),
    ]
