# Generated by Django 5.0.1 on 2024-04-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0017_remove_game_default_categories_court_match_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_winner', to='organisers.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='onGoing_matches',
            field=models.ManyToManyField(blank=True, related_name='tournament_on_going_matches', to='organisers.match'),
        ),
    ]
