# Generated by Django 5.0.1 on 2024-04-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0018_category_winner_tournament_ongoing_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='set_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard_winner', to='organisers.team'),
        ),
    ]
