# Generated by Django 5.0.1 on 2024-04-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0019_scoreboard_set_status_scoreboard_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_set', to='organisers.scoreboard'),
        ),
    ]
