# Generated by Django 5.0.1 on 2024-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0020_match_current_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='venue_link',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Venue Link'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='venue',
            field=models.CharField(default='TBA', max_length=1024, verbose_name='Venue'),
        ),
    ]
